name: block.json Schema Check

on:
  pull_request:
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  validate:
    uses: a8cteam51/team51-configs/.github/workflows/reusable-block-json-check.yml@adec0d882cd5064a7bcc9533d3ebd8bab4a90d5c # update/php85-wp70-floors
