name: JS+CSS Quality Assurance

on:
  pull_request:
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  lint:
    uses: a8cteam51/team51-configs/.github/workflows/reusable-scripts-styles-lint.yml@adec0d882cd5064a7bcc9533d3ebd8bab4a90d5c # update/php85-wp70-floors
