name: JS+CSS Quality Assurance

on:
  push:
    branches: [ trunk, develop ]
  pull_request:
    branches: [ trunk, develop ]

jobs:
  lint-js_css-files:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Setup proper Node.js version
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run JS linter
        run: npm run lint:scripts

      - name: Run CSS linter
        run: npm run lint:styles
